### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by jerryyanmj** [stealthly/go_kafka_client#109]
Try to download the master version, but got this error.
$ go get github.com/stealthly/go_kafka_client
# github.com/stealthly/go_kafka_client
src/github.com/stealthly/go_kafka_client/producer_sarama.go:26: undefined: sarama.Producer

**Comment by serejja** [comment]
Hi @jerryyanmj, please see #110 with updated installation instructions. `go get` tries to build immediately but we need to `gpm install` first before building

**Comment by jerryyanmj** [comment]
I figured it out as you said!!!  Close it now!
Thanks!
