### ISSUE TITLE
Logger allocates strings that are never used

### ISSUE THREAD

**Issue by Fugiman** [stealthly/go_kafka_client#134]
Calls to `Trace` and `Tracef` cause a string allocation even when the log level is set to `INFO`. This generates a lot of garbage, slowing down the garbage collector. In particular the `Trace` calls in [message_buffer.go](https://github.com/stealthly/go_kafka_client/blob/master/message_buffer.go#L140) cause millions of allocations.

I'd be willing to submit a pull request, but am unsure how best to fix this.

**Comment by serejja** [comment]
I think it makes sense to remove that trace messages from message_buffer.go completely as turning on the trace log level will now result in lots of trash in your logs. This was useful when we debugged the consumer on early stages but definitely not now. I think I can make a PR for this today.

Thanks for noticing this.

**Comment by joestein** [comment]
Lets remove traces that aren't necessary and wrap the ones they are conditionally.
