### ISSUE TITLE
Manual commits

### ISSUE THREAD

**Issue by baconalot** [stealthly/go_kafka_client#147]
Right now committing is done every N configured seconds. However I would like to be able to manually commit from the messagehandler, and not have the timed autocommit.

Usecase:
Store reporting data in some other db aggregated per N messages.
Consumer runs over topics, stores aggregated data in temp datastuct and after N records stores that data in some other way. Then and only then a commit of the offsets is performed, and the cycle can start again.

Essentially this would be needed for all multiple record transaction based systems.

**Comment by serejja** [comment]
I doubt we can introduce such a change that would be convenient to use without breaking folks. Go Kafka Client is just was not designed to behave so.

One workaround though that could potentially work is like follows:
1. Have a reference to OffsetStorage somewhere that is being used by this consumer (ZookeeperCoordinator and SiestaClient implement them).
2. In your consumer Strategy always return DoNotCommitOffsetAndContinue and do manual commits via OffsetStorage.CommitOffset(group, topic, partition, offset) when necessary.

Didn't test this approach however.

Thanks and sorry for taking so long to answer.
