### ISSUE TITLE
low level consumer throws invalid memory address on calling go_kafka_client.(*SaramaClient).Initialize

### ISSUE THREAD

**Issue by aartigupta** [stealthly/go_kafka_client#148]
low level consumer throws invalid memory address on calling go_kafka_client.(*SaramaClient).Initialize

note: zookeeper string and kafka string is valid, and tested using kafka console producer and kafka console consumer

2015/08/12 03:42:58 subscription.go:87: Attempting to add subscriber for topic1 aarti
2015/08/12 03:42:58 subscription.go:117: creating consumer:
2015/08/12 03:42:58 subscription.go:122: zookeeper connect is: 172.17.42.1:2181
2015/08/12 03:42:58 server.go:1775: http: panic serving 172.17.42.1:60480: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.func·011()
	/usr/src/go/src/net/http/server.go:1130 +0xbb
github.com/samuel/go-zookeeper/zk.(*Conn).nextXid(0x0, 0x600351)
	/programming/reliable_message_channel_server/src/github.com/samuel/go-zookeeper/zk/conn.go:643 +0x4f
github.com/samuel/go-zookeeper/zk.(*Conn).queueRequest(0x0, 0xc, 0x855720, 0xc208084220, 0x855780, 0xc208030660, 0x0, 0xc2080f1690)
	/programming/reliable_message_channel_server/src/github.com/samuel/go-zookeeper/zk/conn.go:658 +0x28
github.com/samuel/go-zookeeper/zk.(*Conn).request(0x0, 0xc, 0x855720, 0xc208084220, 0x855780, 0xc208030660, 0x0, 0x2, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/samuel/go-zookeeper/zk/conn.go:670 +0x8c
github.com/samuel/go-zookeeper/zk.(*Conn).Children(0x0, 0xa79170, 0xc, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/samuel/go-zookeeper/zk/conn.go:681 +0x127
github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).tryGetAllBrokers(0xc2080f33b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:401 +0x1a3
github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).GetAllBrokers(0xc2080f33b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:387 +0x8f
github.com/stealthly/go_kafka_client.BootstrapBrokers(0x7f2f2a65bf18, 0xc2080f33b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/stealthly/go_kafka_client/low_level_client.go:347 +0xc4
github.com/stealthly/go_kafka_client.(*SaramaClient).Initialize(0xc2080841e0, 0x0, 0x0)
	/programming/reliable_message_channel_server/src/github.com/stealthly/go_kafka_client/low_level_client.go:72 +0x5b
app.createConsumer(0xc2080f1a70, 0xc, 0xc2080841a0, 0x5)
	/programming/reliable_message_channel_server/src/app/subscription.go:127 +0x412

**Comment by serejja** [comment]
This one is probably related to [this commit](https://github.com/samuel/go-zookeeper/commit/4d82abade8e39ed6398e321d284be06ee32ce634) so I bumped `Godeps` in #161.

Closing for now.
