### ISSUE TITLE
panic when i start use config.OffsetStorage = NewSiestaClient(config)

### ISSUE THREAD

**Issue by trueeyu** [stealthly/go_kafka_client#149]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x453c79]

goroutine 35 [running]:
github.com/stealthly/go_kafka_client.(*SiestaClient).GetOffset(0xc20805e160, 0xc2080d605e, 0x11, 0xc2080b3139, 0x5, 0xc200000000, 0x77be00, 0x0, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/low_level_client.go:330 +0x89
github.com/stealthly/go_kafka_client.(*Consumer).fetchOffsets(0xc20807a0b0, 0xc208038100, 0x1, 0x1, 0x1, 0x0, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:785 +0x133
github.com/stealthly/go_kafka_client.tryRebalance(0xc20807a0b0, 0xc2084321b0, 0x9e58e0, 0xc2080d605e)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:708 +0x27b
github.com/stealthly/go_kafka_client.func·011()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:676 +0xe58
github.com/stealthly/go_kafka_client.inLock(0xc20807a0d8, 0xc20842ff08)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/utils.go:44 +0x51
github.com/stealthly/go_kafka_client.(*Consumer).rebalance(0xc20807a0b0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:695 +0x73
github.com/stealthly/go_kafka_client.(*Consumer).reinitializeConsumer(0xc20807a0b0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:305 +0x4e
github.com/stealthly/go_kafka_client.(*Consumer).createMessageStreams(0xc20807a0b0, 0xc20809c780)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:280 +0x190
created by github.com/stealthly/go_kafka_client.(*Consumer).StartStatic
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:110 +0x3c

goroutine 1 [select]:
github.com/stealthly/go_kafka_client.(*Consumer).startStreams(0xc20807a0b0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:188 +0x9f9
github.com/stealthly/go_kafka_client.(*Consumer).StartStatic(0xc20807a0b0, 0xc20809c780)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:112 +0x4c
main.(*DemoConsumer).Start(0xc20801ea00)
	/home/eyu/workspace/src/ac-kafka/demo/simple_consumer/simple_consumer.go:25 +0xa7
main.main()
	/home/eyu/workspace/src/ac-kafka/demo/simple_consumer/simple_consumer.go:66 +0x12b

goroutine 5 [chan receive]:
ac-common-go/glog.(*loggingT).flushDaemon(0xb532e0)
	/home/eyu/workspace/src/ac-common-go/glog/glog.go:868 +0x78
created by ac-common-go/glog.init·1
	/home/eyu/workspace/src/ac-common-go/glog/glog.go:411 +0x31d

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/home/eyu/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 7 [semacquire]:
sync.(*Cond).Wait(0xc20802afc0)
	/home/eyu/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208082000, 0x420200)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208082000)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 8 [semacquire]:
sync.(*Cond).Wait(0xc20802b140)
	/home/eyu/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208082100, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208082100)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 9 [semacquire]:
sync.(*Cond).Wait(0xc20802b6c0)
	/home/eyu/go/src/sync/cond.go:62 +0x9e
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208082280, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:50 +0xe0
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208082280)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 10 [runnable]:
github.com/stealthly/go_kafka_client.(*TopicAndPartition).String(0xc2083ff960, 0x8248e0, 0xc2083ff960)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/structs.go:128
fmt.(*pp).handleMethods(0xc208090000, 0xc200000073, 0x0, 0x1)
	/home/eyu/go/src/fmt/print.go:720 +0x579
fmt.(*pp).printArg(0xc208090000, 0x8248e0, 0xc2083ff960, 0x73, 0x0, 0x0)
	/home/eyu/go/src/fmt/print.go:794 +0x3b8
fmt.(*pp).doPrintf(0xc208090000, 0xc2083ff9c0, 0x1d, 0xc2083ff980, 0x2, 0x2)
	/home/eyu/go/src/fmt/print.go:1183 +0x21cd
fmt.Sprintf(0xc2083ff9c0, 0x1d, 0xc2083ff980, 0x2, 0x2, 0x0, 0x0)
	/home/eyu/go/src/fmt/print.go:203 +0x78
github.com/cihub/seelog.(*logFormattedMessage).String(0xc2080b5d70, 0x0, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/logger.go:361 +0x62
github.com/cihub/seelog.(*commonLogger).processLogMsg(0xc208082400, 0x86b802, 0x7f04efa14a60, 0xc2080b5d70, 0x7f04efa14a88, 0xc20843e180)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/logger.go:304 +0x8a
github.com/cihub/seelog.(*asyncLogger).processQueueElement(0xc208082400)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclogger.go:115 +0xd3
github.com/cihub/seelog.(*asyncLoopLogger).processItem(0xc208082400, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:57 +0x132
github.com/cihub/seelog.(*asyncLoopLogger).processQueue(0xc208082400)
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:63 +0x47
created by github.com/cihub/seelog.newAsyncLoopLogger
	/home/eyu/workspace/src/ac-kafka/src/github.com/cihub/seelog/behavior_asynclooplogger.go:40 +0x8e

goroutine 18 [semacquire]:
sync.(*WaitGroup).Wait(0xc20805e1e0)
	/home/eyu/go/src/sync/waitgroup.go:132 +0x169
github.com/samuel/go-zookeeper/zk.(*Conn).loop(0xc2080b80e0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:287 +0x78c
github.com/samuel/go-zookeeper/zk.func·001()
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:185 +0x2c
created by github.com/samuel/go-zookeeper/zk.ConnectWithDialer
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:189 +0x606

goroutine 19 [chan receive]:
github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).listenConnectionEvents(0xc20803ade0, 0xc2080e0060)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:90 +0x68
created by github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).Connect
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:67 +0xe1

goroutine 15 [select]:
github.com/Shopify/sarama.(*client).backgroundMetadataUpdater(0xc2080b6000)
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/client.go:553 +0x2f3
github.com/Shopify/sarama.*client.(github.com/Shopify/sarama.backgroundMetadataUpdater)·fm()
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/client.go:142 +0x27
github.com/Shopify/sarama.withRecover(0xc20800af10)
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/utils.go:42 +0x3a
created by github.com/Shopify/sarama.NewClient
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/client.go:142 +0x8ce

goroutine 11 [select]:
github.com/samuel/go-zookeeper/zk.(*Conn).sendLoop(0xc2080b80e0, 0x7f04efa14ea8, 0xc2080ec010, 0xc2080347e0, 0x0, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:483 +0xce9
github.com/samuel/go-zookeeper/zk.func·002()
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:272 +0x5a
created by github.com/samuel/go-zookeeper/zk.(*Conn).loop
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:275 +0x69f

goroutine 12 [IO wait]:
net.(*pollDesc).Wait(0xc2080100d0, 0x72, 0x0, 0x0)
	/home/eyu/go/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080100d0, 0x0, 0x0)
	/home/eyu/go/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc208010070, 0xc208276000, 0x4, 0x180000, 0x0, 0x7f04efa10fb8, 0xc20843a670)
	/home/eyu/go/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc2080ec010, 0xc208276000, 0x4, 0x180000, 0x0, 0x0, 0x0)
	/home/eyu/go/src/net/net.go:121 +0xdc
io.ReadAtLeast(0x7f04efa15f68, 0xc2080ec010, 0xc208276000, 0x4, 0x180000, 0x4, 0x0, 0x0, 0x0)
	/home/eyu/go/src/io/io.go:298 +0xf1
io.ReadFull(0x7f04efa15f68, 0xc2080ec010, 0xc208276000, 0x4, 0x180000, 0x0, 0x0, 0x0)
	/home/eyu/go/src/io/io.go:316 +0x6d
github.com/samuel/go-zookeeper/zk.(*Conn).recvLoop(0xc2080b80e0, 0x7f04efa14ea8, 0xc2080ec010, 0x0, 0x0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:547 +0x1b6
github.com/samuel/go-zookeeper/zk.func·003()
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:279 +0x5f
created by github.com/samuel/go-zookeeper/zk.(*Conn).loop
	/home/eyu/workspace/src/ac-kafka/src/github.com/samuel/go-zookeeper/zk/conn.go:285 +0x77c

goroutine 14 [chan receive]:
github.com/Shopify/sarama.(*Broker).responseReceiver(0xc2080da070)
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/broker.go:345 +0xe3
github.com/Shopify/sarama.*Broker.(github.com/Shopify/sarama.responseReceiver)·fm()
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/broker.go:98 +0x27
github.com/Shopify/sarama.withRecover(0xc20800ac20)
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/utils.go:42 +0x3a
created by github.com/Shopify/sarama.func·006
	/home/eyu/workspace/src/ac-kafka/src/github.com/Shopify/sarama/broker.go:98 +0x666

goroutine 16 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0xb52f40)
	/home/eyu/workspace/src/ac-kafka/src/github.com/rcrowley/go-metrics/meter.go:221 +0x52
created by github.com/rcrowley/go-metrics.NewMeter
	/home/eyu/workspace/src/ac-kafka/src/github.com/rcrowley/go-metrics/meter.go:40 +0x1f7

goroutine 34 [chan receive]:
github.com/stealthly/go_kafka_client.func·001()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:95 +0x48
created by github.com/stealthly/go_kafka_client.NewConsumer
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:99 +0x76f

goroutine 36 [select]:
github.com/stealthly/go_kafka_client.func·003()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:231 +0x2c9
created by github.com/stealthly/go_kafka_client.(*Consumer).maintainCleanCoordinator
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:239 +0xdf

goroutine 22 [select]:
reflect.Select(0xc2080ae1c0, 0x5, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/eyu/go/src/reflect/value.go:1965 +0x218
github.com/stealthly/go_kafka_client.func·035()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/utils.go:197 +0x7a
created by github.com/stealthly/go_kafka_client.redirectChannelsToWithTimeout
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/utils.go:216 +0xbdb

goroutine 23 [select]:
github.com/stealthly/go_kafka_client.func·050()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:511 +0x1634
created by github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).trySubscribeForChanges
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:562 +0xbdb

goroutine 24 [select]:
github.com/stealthly/go_kafka_client.func·010()
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:584 +0x510
created by github.com/stealthly/go_kafka_client.(*Consumer).subscribeForChanges
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/consumer.go:621 +0x1dc

goroutine 25 [chan receive]:
github.com/stealthly/go_kafka_client.func·051(0xc20808d6e0)
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:757 +0x3d
created by github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).waitForMembersToJoin
	/home/eyu/workspace/src/ac-kafka/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:773 +0x45e

**Comment by serejja** [comment]
Can you attach code that causes this please?

**Comment by trueeyu** [comment]
if I remove the :   consumerConfig.OffsetStorage = go_kafka_client.NewSiestaClient(consumerConfig)
it will be ok

func main() {
  log.Flush()
  runtime.GOMAXPROCS(runtime.NumCPU())
  consumerConfig, err := go_kafka_client.ConsumerConfigFromFile("../../kafka_config/consumer.conf")
  if err != nil || consumerConfig == nil {
    log.Warningf("read consumer config failed: err[%v]", err)
    return
  }
  consumerConfig.WorkerFailureCallback = failedCallBack
  consumerConfig.WorkerFailedAttemptCallback = failedAttemptCallBack
  consumerConfig.Strategy = NewMessageFunc()

  consumerConfig.OffsetStorage = go_kafka_client.NewSiestaClient(consumerConfig)
  consumer := go_kafka_client.NewConsumer(consumerConfig)
  consumer.StartStatic(map[string]int{"test1": 1}) 
  return
}

**Comment by trueeyu** [comment]
this is the error log of zookeeper


[2015-08-28 15:36:58,974] WARN Connection request from old client /127.0.0.1:50515; will be dropped if server is in r-o mode (org.apache.zookeeper.server.ZooKeeperServer)
[2015-08-28 15:36:58,974] INFO Client attempting to establish new session at /127.0.0.1:50515 (org.apache.zookeeper.server.ZooKeeperServer)
[2015-08-28 15:36:58,984] INFO Established session 0x14f7224bb3b0028 with negotiated timeout 6000 for client /127.0.0.1:50515 (org.apache.zookeeper.server.ZooKeeperServer)
[2015-08-28 15:36:58,987] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0x5 zxid:0x2c5 txntype:-1 reqpath:n/a Error Path:/consumers Error:KeeperErrorCode = NodeExists for /consumers (org.apache.zookeeper.server.PrepRequestProcessor)
[2015-08-28 15:36:59,020] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0x6 zxid:0x2c6 txntype:-1 reqpath:n/a Error Path:/consumers/go-consumer-group Error:KeeperErrorCode = NodeExists for /consumers/go-consumer-group (org.apache.zookeeper.server.PrepRequestProcessor)
[2015-08-28 15:36:59,033] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0x7 zxid:0x2c7 txntype:-1 reqpath:n/a Error Path:/consumers/go-consumer-group/ids Error:KeeperErrorCode = NodeExists for /consumers/go-consumer-group/ids (org.apache.zookeeper.server.PrepRequestProcessor)
[2015-08-28 15:36:59,042] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0x8 zxid:0x2c8 txntype:-1 reqpath:n/a Error Path:/consumers/go-consumer-group/api Error:KeeperErrorCode = NodeExists for /consumers/go-consumer-group/api (org.apache.zookeeper.server.PrepRequestProcessor)
[2015-08-28 15:36:59,050] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0x9 zxid:0x2c9 txntype:-1 reqpath:n/a Error Path:/consumers/go-consumer-group/api/blue_green Error:KeeperErrorCode = NodeExists for /consumers/go-consumer-group/api/blue_green (org.apache.zookeeper.server.PrepRequestProcessor)
[2015-08-28 15:36:59,058] INFO Got user-level KeeperException when processing sessionid:0x14f7224bb3b0028 type:create cxid:0xa zxid:0x2ca txntype:-1 reqpath:n/a Error Path:/consumers/go-consumer-group/api/rebalance Error:KeeperErrorCode = NodeExists for /consumers/go-consumer-group/api/rebalance (org.apache.zookeeper.server.PrepRequestProcessor)

**Comment by serejja** [comment]
Hi @trueeyu

Sorry for taking so long to answer.
Can you please post contents of your `consumer.conf` or post a minimal working example so I don't miss any configurations that are important to cause this? So far works fine for me.

Thanks!

**Comment by trueeyu** [comment]
#A string that uniquely identifies a set of consumers within the same consumer group
group.id=go-consumer-group

#A string that uniquely identifies a consumer within a group. Generated automatically if not set.
#Set this explicitly for only testing purpose.
consumer.id=1

#The socket timeout for network requests. Its value should be at least FetchWaitMaxMs.
socket.timeout=30s

#The maximum number of bytes to attempt to fetch
fetch.message.max.bytes=1048576

#The number of goroutines used to fetch data
num.consumer.fetchers=1

#Max number of message batches buffered for consumption, each batch can be up to FetchBatchSize
queued.max.message.chunks=3

#Max number of retries during rebalance
rebalance.max.retries=4

#The minimum amount of data the server should return for a fetch request.
#If insufficient data is available the request will block
fetch.min.bytes=1

#The maximum amount of time the server will block before answering the fetch request
#if there isn't sufficient data to immediately satisfy FetchMinBytes
fetch.wait.max.ms=100

#Backoff time between retries during rebalance
rebalance.backoff=5s

#Backoff time to refresh the leader of a partition after it loses the current leader
refresh.leader.backoff=200ms

#Retry the offset commit up to this many times on failure.
offset.commit.max.retries=10

#Try to commit offset every OffsetCommitInterval.
#If previous offset commit for a partition is still in progress updates the next offset to commit and continues.
#This way it does not commit all the offset history if the coordinator is slow, but only the highest offsets.
offset.commit.interval=3s

#What to do if an offset is out of range.
#SmallestOffset : automatically reset the offset to the smallest offset.
#LargestOffset : automatically reset the offset to the largest offset.
#Defaults to LargestOffset.
auto.offset.reset=largest

#Whether messages from internal topics (such as offsets) should be exposed to the consumer.
exclude.internal.topics=true

#Select a strategy for assigning partitions to consumer streams. Possible values: RangeStrategy, RoundRobinStrategy
partition.assignment.strategy=range

#Amount of workers per partition to process consumed messages.
num.workers=10

#Times to retry processing a failed message by a worker.
max.worker.retries=3

#Worker retry threshold. Increments each time a worker fails to process a message within MaxWorkerRetries.
#When this threshold is hit within a WorkerThresholdTimeWindow,
#WorkerFailureCallback is called letting the user to decide whether the consumer should stop.
worker.retry.threshold=100

#Resets WorkerRetryThreshold if it isn't hit within this period.
worker.threshold.time.window=1m

#Worker timeout to process a single message.
worker.task.timeout=1m

#Backoff between worker attempts to process a single message.
worker.backoff=500ms

#Maximum wait time to gracefully stop a worker manager
worker.managers.stop.timeout=1m

#Number of messages to accumulate before flushing them to workers
fetch.batch.size=100

#Timeout to accumulate messages. Flushes accumulated batch to workers even if it is not yet full.
#Resets after each flush meaning this won't be triggered if FetchBatchSize is reached before timeout.
fetch.batch.timeout=5s

#Backoff between fetch requests if no messages were fetched from a previous fetch.
requeue.ask.next.backoff=5s

#Maximum fetch retries if no messages were fetched from a previous fetch
fetch.max.retries=5

#Maximum retries to fetch topic metadata from one broker.
fetch.topic.metadata.retries=3

#Backoff for fetch topic metadata request if the previous request failed.
fetch.topic.metadata.backoff=1s

#Backoff between two fetch requests for one fetch routine.
#Needed to prevent fetcher from querying the broker too frequently.
fetch.request.backoff=10m

#Indicates whether the client supports blue-green deployment.
#This config entry is needed because blue-green deployment won't work with RoundRobin partition assignment strategy.
#Defaults to true.
blue.green.deployment.enabled=true

**Comment by serejja** [comment]
Hi.

You shouldn't use siesta low level client alone as offset storage. To avoid this panic you should use like this:

```
client := go_kafka_client.NewSiestaClient(consumerConfig)
consumerConfig.LowLevelClient = client
consumerConfig.OffsetStorage = client
```

**Comment by trueeyu** [comment]
add

client := go_kafka_client.NewSiestaClient(consumerConfig)
consumerConfig.LowLevelClient = client
consumerConfig.OffsetStorage = client

the error log:

2015-09-21/22:35:49 [INFO] [zk] Joining state barrier /consumers/go-consumer-group/api/rebalance/76e01d92711ed94845de248503a0d648
2015-09-21/22:35:49 [INFO] [zk] Barrier already exists with deadline set to 2015-09-21 22:35:51 +0800 CST. Joining...
2015-09-21/22:35:49 [INFO] [zk] Successfully joined state barrier /consumers/go-consumer-group/api/rebalance/76e01d92711ed94845de248503a0d648
2015-09-21/22:35:49 [INFO] [zk] Successfully awaited on state barrier 76e01d92711ed94845de248503a0d648
2015-09-21/22:35:49 [INFO] [1] {1 %!s(int=0)} attempting to claim {Topic: test1, Partition: 0}
2015-09-21/22:35:49 [WARN] [Default Connector] Could not get topic metadata from all known brokers, trying bootstrap brokers...
2015-09-21/22:35:49 [ERROR] [1] Failed to fetch offsets during rebalance: This request is for a topic or partition that does not exist on this broker.

if i remove the code ,it will be ok

**Comment by serejja** [comment]
Sorry, my bad. Please try #163, this should be fixed now

**Comment by trueeyu** [comment]
it works! good job! thank you!!!!
