### ISSUE TITLE
SiestaClient not commiting offsets with Go Kafka Client

### ISSUE THREAD

**Issue by pfischermx** [stealthly/go_kafka_client#154]
Hello,

Not sure if this git issue should go here or to the Siesta client. We recently modified mirror_maker.go to force it to use SiestaClient as the low level client and after adding some minor debugging we can verify that it is trying to get the brokers from ZK.

However we are having hard time in getting it to commit the offset, it is just not even trying to call the CommitOffset function (inside low_level.client), are we missing something really obvious?

config.LowLevelClient = NewSiestaClient(config)

Thx!

**Comment by serejja** [comment]
Hi @pfischermx,

this one is really not obvious and we'll have to make some backwards incompatible changes later to make things clearer.

The thing you are missing is `config.OffsetStorage`

e.g. a following code snippet should work in your case:

```
siestaClient := NewSiestaClient(config)
config.LowLevelClient = siestaClient
config.OffsetStorage = siestaClient
```

Sorry for taking so long to answer.
Thanks!
