### ISSUE TITLE
Panic thrown when Zookeeper Node Restarts

### ISSUE THREAD

**Issue by carnellj** [stealthly/go_kafka_client#156]
Hi guys,

Here is the situation.  We are using the GO Kafka Client to create a consumer listening to kafka.  Our DevOps was doing a rolling upgrade to the Zookeeper cluster that our Kafka cluster uses.  When the zookeeper node that the client listens to went down, we errors being written out that the server was unavailable, but out service stayed up and at least to process connections.

However, when the Zookeeper node that was down restarted the GO_Kafka Client threw a Panic at we traced the problem back to the zk_coordinator.go trySubscribeForChanges()'s function.  Here is the specific part of the trace we tracked it down to.

**
github.com/stealthly/go_kafka_client.func·050()
/Users/matt.durham/repos/edge-proxy/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:528 +0x992
created by github.com/stealthly/go_kafka_client.(*ZookeeperCoordinator).trySubscribeForChanges
/Users/matt.durham/repos/edge-proxy/src/github.com/stealthly/go_kafka_client/zk_coordinator.go:562 +0xbdb
**

Is this a bug or is this expected behavior?  It seems like the consumer is tied to a specific zookeeperConnection and does not refresh after the connection has been re-established.   Any help here would be greatly appreciated.

**Comment by serejja** [comment]
Hi @carnellj 

Can you please try #159 and reply if this works for you?

Thanks!

**Comment by serejja** [comment]
@carnellj can we close this?

**Comment by carnellj** [comment]
Yes.  Thank you for the help.
