### ISSUE TITLE
 Godeps lists the wrong version of jimlawless/cfg

### ISSUE THREAD

**Issue by stew** [stealthly/go_kafka_client#157]
Godeps file is currently referencing commit 4b1e3c1869d4e608fcbda6994e5f08dd9c6beaa1, however the upstream siesta project uses the LoadNewMap method from cfg which was not added until the commit after we are specifying.  Updating this dep to the latetst: 8cf9686de5a8b290717494297d381948feffe19f seems to get things building again.

**Comment by serejja** [comment]
Fixed in #158 

One thing to mention though is we are going to move to [godep](https://github.com/tools/godep) dependency manager once #153 is merged to be uniform with [mesos-go](https://github.com/mesos/mesos-go) so we'll have to review dependency list once more.
