### ISSUE TITLE
Consuming multiple topics

### ISSUE THREAD

**Issue by mihasya** [stealthly/go_kafka_client#86]
Hey guys, I'm observing some strange behavior, and I was wondering if I'm doing something wrong..

My goals are fairly simple:

* Consume 2 topics, one with 16 partitions, one with 4.
* Each topic has its own "Strategy", e.g they contain different "types" of jobs
* I want to have 2 instances of the consumer service active at all times. I would prefer that they distribute the work evenly, but I do not mind if it all goes to one of them for the time being, as long as it keeps up.
* It is important to me that if one of the consumer services dies, the other is able to "steal" all of the partitions.

Based on my understanding of this library, the above goals are basically exactly what it was written for. Here is what I am experiencing:

Originally there was only 1 topic, the 16 partition one. We were able to implement that no problem once @evanjones figured out the issue he fixed [here](https://github.com/stealthly/go_kafka_client/pull/73).

My first stab at adding the second topic was to create a second `Consumer` from a second instance of `ConsumerConfig`, with its own `Strategy`, `WorkerFailureCallback` and `WorkerFailedAttemptCallback`. I was calling `StartStatic` on each instance, passing the appropriate topic/consumer map to each. Each got a map with just one key in it (the respective topic) with the value 16, since I do want each single instance of the consumer service to be able to process all the partitions in the bigger topic should the other instance die.

When I started the service up with this configuration, even if I was only starting one instance of the service, the consumer could never quite get past the "Joining state barrier" phase - it would just repeat the same set of 4 messages about "Commencing assertion" and "Joining state barrier" at intervals. Pressed for time, I thought "Fine, the `Strategy` function does get the topic from which the message came passed to it, so I'll just implement a strategy that can handle a number of topics, create a single instance of `Consumer` with that `Strategy`, and call `StartStatic` once with a map of multiple keys." So I wrote [this little wrapper](https://gist.github.com/mihasya/8d5536c881d8292049dc).

This seemed to initialize fine, but in spite of running two copies of the service, the second smaller topic does not appear to be getting processed in full (I'm still working on setting up monitoring to see exactly which partitions are and are not being processed; the fact that NO offsets have been committed for one of the partitions by the worker group is breaking `kafka.tools.ConsumerOffsetChecker`, which is how we were exporting the data before, and I have not figured out a better way yet). It also appears as if jobs that ARE being processed are getting processed twice, at least based on the logs I'm seeing.

I thought I would post here and see if I am making some common mistake or falling into a known pitfall before I went gangbusters writing a reproduction and digging deep into the code. Do you have any advice for isolating the issue and for figuring out exactly what each consumer is doing or trying to do? If we find a bug here, I'll happily contribute a patch, but I do remain optimistic that I'm simply mis-using the library :)

**Comment by serejja** [comment]
Hey @mihasya can you please reply whether we can close this now? Thanks

**Comment by mihasya** [comment]
:+1: my bad for not circling back, confirmed this bug is fixed.
